
import java.awt.Image;
import java.io.*;
import java.sql.*;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.*;

public class AddEpisodes extends javax.swing.JInternalFrame
{

    /**
     * Creates new form AddEpisodes
     */
    File f;

    public AddEpisodes()
    {
        initComponents();
        tvShow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbtvshow = new javax.swing.JComboBox<>();
        tftitle = new javax.swing.JTextField();
        lbvideopath = new javax.swing.JLabel();
        lbcoverphoto = new javax.swing.JLabel();
        lbsquarephoto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfhh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfmm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btvideobrowse = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btcoverbrowse = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btsquarebrowse = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btaddepisode = new javax.swing.JButton();

        getContentPane().setLayout(null);

        cbtvshow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cbtvshow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbtvshowActionPerformed(evt);
            }
        });
        getContentPane().add(cbtvshow);
        cbtvshow.setBounds(171, 11, 353, 37);
        getContentPane().add(tftitle);
        tftitle.setBounds(171, 66, 353, 37);
        getContentPane().add(lbvideopath);
        lbvideopath.setBounds(171, 121, 353, 72);
        getContentPane().add(lbcoverphoto);
        lbcoverphoto.setBounds(171, 211, 100, 72);
        getContentPane().add(lbsquarephoto);
        lbsquarephoto.setBounds(171, 301, 100, 72);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("HH:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(172, 391, 22, 24);
        getContentPane().add(tfhh);
        tfhh.setBounds(200, 391, 30, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("MM:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 390, 26, 24);
        getContentPane().add(tfmm);
        tfmm.setBounds(270, 390, 30, 24);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Select TV Show");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 11, 153, 37);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Title");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 66, 155, 37);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Video Path");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 121, 155, 37);

        btvideobrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btvideobrowse.setText("Browse...");
        btvideobrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btvideobrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btvideobrowse);
        btvideobrowse.setBounds(10, 170, 80, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cover Photo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 211, 155, 37);

        btcoverbrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcoverbrowse.setText("Browse...");
        btcoverbrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btcoverbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btcoverbrowse);
        btcoverbrowse.setBounds(10, 259, 80, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Square Photo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 301, 155, 37);

        btsquarebrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btsquarebrowse.setText("Browse...");
        btsquarebrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btsquarebrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btsquarebrowse);
        btsquarebrowse.setBounds(10, 349, 89, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Duration");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(16, 401, 155, 15);

        btaddepisode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btaddepisode.setText("Add Episode");
        btaddepisode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btaddepisodeActionPerformed(evt);
            }
        });
        getContentPane().add(btaddepisode);
        btaddepisode.setBounds(80, 434, 206, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btvideobrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btvideobrowseActionPerformed
    {//GEN-HEADEREND:event_btvideobrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                lbvideopath.setText(f.getPath());

            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btvideobrowseActionPerformed

    private void btcoverbrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btcoverbrowseActionPerformed
    {//GEN-HEADEREND:event_btcoverbrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                lbcoverphoto.setText(f.getPath());
                Image img = ImageIO.read(f).getScaledInstance(lbcoverphoto.getWidth(), lbcoverphoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbcoverphoto.setIcon(icon);
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btcoverbrowseActionPerformed

    private void btsquarebrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btsquarebrowseActionPerformed
    {//GEN-HEADEREND:event_btsquarebrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                lbsquarephoto.setText(f.getPath());
                Image img = ImageIO.read(f).getScaledInstance(lbsquarephoto.getWidth(), lbsquarephoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbsquarephoto.setIcon(icon);
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btsquarebrowseActionPerformed

    private void cbtvshowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbtvshowActionPerformed
    {//GEN-HEADEREND:event_cbtvshowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtvshowActionPerformed

    private void btaddepisodeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btaddepisodeActionPerformed
    {//GEN-HEADEREND:event_btaddepisodeActionPerformed
        String tvshow = cbtvshow.getSelectedItem() + "";
        String title = tftitle.getText();
        String videopath = lbvideopath.getText();
        String coverphoto = lbcoverphoto.getText();
        String squarephoto = lbsquarephoto.getText();
        String duration = tfhh.getText() + ":" + tfmm.getText();
        if (title.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Title field");
        } else if (videopath.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Video Path field");
        } else if (coverphoto.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Cover Photo field");
        } else if (squarephoto.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Square Photo field");
        } else if (duration.equals(":"))
        {
            JOptionPane.showMessageDialog(this, "Please fill the Duration field");
        } else
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod", "root", "system");
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                int selectedIndex = cbtvshow.getSelectedIndex();
                Tvshow tvshow1 = altvshows.get(selectedIndex);

                String id = tvshow1.vid;
                ResultSet rs = stmt.executeQuery("select * from episodes");
                rs.moveToInsertRow();
                rs.updateString("title", title);
                rs.updateString("videopath", videopath);
                rs.updateString("cover", coverphoto);
                rs.updateString("square", squarephoto);
                rs.updateString("duration", duration);
                rs.updateString("vid", id);
                rs.insertRow();
                JOptionPane.showMessageDialog(this, "Episode add Successfully");
                
            } catch (Exception e)
            {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btaddepisodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddepisode;
    private javax.swing.JButton btcoverbrowse;
    private javax.swing.JButton btsquarebrowse;
    private javax.swing.JButton btvideobrowse;
    private javax.swing.JComboBox<String> cbtvshow;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbcoverphoto;
    private javax.swing.JLabel lbsquarephoto;
    private javax.swing.JLabel lbvideopath;
    private javax.swing.JTextField tfhh;
    private javax.swing.JTextField tfmm;
    private javax.swing.JTextField tftitle;
    // End of variables declaration//GEN-END:variables

   
    ArrayList<Tvshow> altvshows = new ArrayList<>();

    void tvShow()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod", "root", "system");
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery("select * from video where cname='" + "TV Shows" + "'");
            while (rs.next())
            {
                String title = rs.getString("title");
                String id = rs.getString("id");
                cbtvshow.addItem(title);
                altvshows.add(new Tvshow(id, title));
            }
        } catch (Exception e)
        {
        }

    }
}
 class Tvshow
    {

        String vid;
        String title;

        public Tvshow(String id, String title)
        {
            this.vid = id;
            this.title = title;
        }

    }
