
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class EditTvShow extends javax.swing.JInternalFrame
{

    /**
     * Creates new form EditTvShow
     */
    File f;
    String movietitle;
    public EditTvShow(String genre,String producer,String director,String storyline,String id,String movietitle,String duration
                                               ,String rating,String language,String coverphoto,String squarephoto)
    {
        f=new File("");
        this.movietitle=movietitle;
        initComponents();
         cbGenre();
        cbgenre.setSelectedItem(genre);
        tfproducer.setText(producer);
        tfdirector.setText(director);
        tastoryline.setText(storyline);
        tftitle.setText(movietitle);
        tfhh.setText(duration.substring(0, 1));
        tfmm.setText(duration.substring(2, 4));
        cbrating.setSelectedItem(rating);
        cblanguage.setSelectedItem(language);
        lbcover.setText(coverphoto);
        lbsquare.setText(squarephoto);
        try
        {
            Image img = ImageIO.read(new File(lbsquare.getText())).getScaledInstance(lbsquare.getWidth(), lbsquare.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lbsquare.setIcon(icon);
        } catch (Exception e)
        {
            e.printStackTrace();
        }
        try
        {
           
            Image img = ImageIO.read(new File(lbcover.getText())).getScaledInstance(lbcover.getWidth(), lbcover.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lbcover.setIcon(icon);
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbgenre = new javax.swing.JComboBox<>();
        tfproducer = new javax.swing.JTextField();
        tfdirector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tastoryline = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        tftitle = new javax.swing.JTextField();
        tfhh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfmm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbrating = new javax.swing.JComboBox<>();
        cblanguage = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btcoverbrowse = new javax.swing.JButton();
        btserverbrowse = new javax.swing.JButton();
        btaddtodatabase = new javax.swing.JButton();
        lbcover = new javax.swing.JLabel();
        lbsquare = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        cbgenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cbgenre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbgenreActionPerformed(evt);
            }
        });
        getContentPane().add(cbgenre);
        cbgenre.setBounds(170, 60, 125, 34);

        tfproducer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfproducerActionPerformed(evt);
            }
        });
        getContentPane().add(tfproducer);
        tfproducer.setBounds(170, 110, 125, 34);

        tfdirector.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfdirectorActionPerformed(evt);
            }
        });
        getContentPane().add(tfdirector);
        tfdirector.setBounds(170, 170, 125, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Genre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 128, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Producer");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 132, 33);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Director");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 134, 33);

        tastoryline.setColumns(20);
        tastoryline.setRows(5);
        jScrollPane1.setViewportView(tastoryline);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 230, 166, 96);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Story Line");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 128, 32);
        getContentPane().add(tftitle);
        tftitle.setBounds(170, 350, 162, 31);

        tfhh.setText("00");
        getContentPane().add(tfhh);
        tfhh.setBounds(790, 360, 32, 30);

        jLabel6.setText("HH:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(770, 360, 18, 30);

        jLabel7.setText("MM:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(840, 360, 20, 30);

        tfmm.setText("00");
        getContentPane().add(tfmm);
        tfmm.setBounds(860, 360, 32, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Video Title");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 350, 130, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Duration");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(630, 360, 130, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Rating");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 60, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Language");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(630, 110, 110, 34);

        cbrating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 (Excellent)", "4 (Verygood)", "3 (Good)", "2 (Poor)","1 (Verypoor)" }));
        cbrating.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbratingActionPerformed(evt);
            }
        });
        getContentPane().add(cbrating);
        cbrating.setBounds(740, 60, 125, 35);

        cblanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Hindi", "Punjabi"}));
        cblanguage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cblanguageActionPerformed(evt);
            }
        });
        getContentPane().add(cblanguage);
        cblanguage.setBounds(740, 110, 125, 34);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cover Photo");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(630, 150, 126, 37);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Square Photo");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(630, 250, 100, 30);

        btcoverbrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcoverbrowse.setText("Browse...");
        btcoverbrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btcoverbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btcoverbrowse);
        btcoverbrowse.setBounds(630, 190, 90, 23);

        btserverbrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btserverbrowse.setText("Browse...");
        btserverbrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btserverbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btserverbrowse);
        btserverbrowse.setBounds(630, 290, 90, 23);

        btaddtodatabase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btaddtodatabase.setText("Update");
        btaddtodatabase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btaddtodatabaseActionPerformed(evt);
            }
        });
        getContentPane().add(btaddtodatabase);
        btaddtodatabase.setBounds(370, 420, 246, 73);
        getContentPane().add(lbcover);
        lbcover.setBounds(740, 160, 160, 80);
        getContentPane().add(lbsquare);
        lbsquare.setBounds(750, 260, 160, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void cbGenre()
   {
     try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod","root","system");
        Statement stmt=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        ResultSet rs=stmt.executeQuery("select * from genre");
        while(rs.next())
        {
            String selectgenre=rs.getString("Genre Name");
            cbgenre.addItem(selectgenre);
            
        }
        }
        catch(Exception ex)
        {
            
        }   
   }
    private void btcoverbrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btcoverbrowseActionPerformed
    {//GEN-HEADEREND:event_btcoverbrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                lbcover.setText(f.getPath());
                Image img = ImageIO.read(f).getScaledInstance(lbcover.getWidth(), lbcover.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbcover.setIcon(icon);
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btcoverbrowseActionPerformed

    private void cbgenreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbgenreActionPerformed
    {//GEN-HEADEREND:event_cbgenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgenreActionPerformed

    private void tfproducerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfproducerActionPerformed
    {//GEN-HEADEREND:event_tfproducerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfproducerActionPerformed

    private void tfdirectorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfdirectorActionPerformed
    {//GEN-HEADEREND:event_tfdirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdirectorActionPerformed

    private void cblanguageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cblanguageActionPerformed
    {//GEN-HEADEREND:event_cblanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cblanguageActionPerformed
    String squarephoto="";
    private void btserverbrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btserverbrowseActionPerformed
    {//GEN-HEADEREND:event_btserverbrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                squarephoto = f.getPath();
                lbsquare.setText(f.getPath());
                Image img = ImageIO.read(f).getScaledInstance(lbsquare.getWidth(), lbsquare.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbsquare.setIcon(icon);
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btserverbrowseActionPerformed

    private void btaddtodatabaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btaddtodatabaseActionPerformed
    {//GEN-HEADEREND:event_btaddtodatabaseActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod", "root", "system");
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            // ResultSet rs = stmt.executeQuery("select * from video");

            //  rs.moveToInsertRow();

            
            String genre = cbgenre.getSelectedItem() + "";
            String producer = tfproducer.getText();
            String director = tfdirector.getText();
            String storyline = tastoryline.getText();
            String videotitle = tftitle.getText();
            String durationhh = tfhh.getText();
            String durationmm = tfmm.getText();
            String duration = durationhh + ":" + durationmm;
            String rating = cbrating.getSelectedItem() + "";
            String language = cblanguage.getSelectedItem() + "";
            String coverphoto = lbcover.getText();
            String squarephoto = lbsquare.getText();
            if (producer.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please fill Producer field");
            } else if (director.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please fill director field");
            } else if (storyline.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please fill storyline field");
            } else if (videotitle.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please fill Video Title field");
            } else if (duration.equals(":"))
            {
                JOptionPane.showMessageDialog(this, "Please fill Duration field");
            } else if (coverphoto.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please fill Cover Photo field");
            } else if (squarephoto.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please fill Square Photo field");
            } else
            {
                ResultSet rs = stmt.executeQuery("select * from video where title='"+movietitle+"'");
                if(rs.next())
                {
                   
                    
                    rs.updateString("genre", genre);
                    rs.updateString("producer", producer);
                    rs.updateString("director", director);
                    rs.updateString("storyline", storyline);
                    rs.updateString("title", videotitle);
                    rs.updateString("duration", duration);
                    rs.updateString("rating", rating);
                    rs.updateString("language", language);
                    rs.updateString("coverphoto", coverphoto);
                    rs.updateString("squarephoto", squarephoto);
                    rs.updateString("cast", "");
                    rs.updateString("videopath", "");
                    rs.updateString("trailerpath", "");
                    rs.updateString("releasedate", "");
                    rs.updateRow();
                    JOptionPane.showMessageDialog(this, "Video Updated");
                    this.dispose();
                }
            }

        } catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btaddtodatabaseActionPerformed

    private void cbratingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbratingActionPerformed
    {//GEN-HEADEREND:event_cbratingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbratingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddtodatabase;
    private javax.swing.JButton btcoverbrowse;
    private javax.swing.JButton btserverbrowse;
    private javax.swing.JComboBox<String> cbgenre;
    private javax.swing.JComboBox<String> cblanguage;
    private javax.swing.JComboBox<String> cbrating;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcover;
    private javax.swing.JLabel lbsquare;
    private javax.swing.JTextArea tastoryline;
    private javax.swing.JTextField tfdirector;
    private javax.swing.JTextField tfhh;
    private javax.swing.JTextField tfmm;
    private javax.swing.JTextField tfproducer;
    private javax.swing.JTextField tftitle;
    // End of variables declaration//GEN-END:variables
}
