
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class EditEpisodes extends javax.swing.JInternalFrame
{

    /**
     * Creates new form EditEpisodes
     */
    File f;
    JFileChooser jfilechooser;
    String title;
    String coverphoto;
    String squarephoto;
    String videopath;
    int eid;
    String duration;


    public EditEpisodes(String title,String videopath,String coverphoto,String squarephoto,String duration,Object selected,int eid)
    {
        initComponents();
           this.title=title;
           this.squarephoto=squarephoto;
           this.coverphoto=coverphoto;
           this.videopath=videopath;
           this.duration=duration;
           this.eid=eid;
           cbtvshow.setSelectedItem(selected);
           tftitle.setText(title);
           lbvideopath.setText(videopath);
           lbcoverphoto.setText(coverphoto);
           System.out.println(squarephoto);
           lbsquarephoto.setText(squarephoto);
            try
            {
               Image img = ImageIO.read(new File(lbsquarephoto.getText())).getScaledInstance(lbsquarephoto.getWidth(), lbsquarephoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lbsquarephoto.setIcon(icon);
            } catch (Exception e)
            {
             e.printStackTrace();
            }
        try
        {
            
            Image img = ImageIO.read(new File(lbcoverphoto.getText())).getScaledInstance(lbcoverphoto.getWidth(), lbcoverphoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lbcoverphoto.setIcon(icon);
        } catch (Exception e)
        {
            e.printStackTrace();
        }
           tfhh.setText(duration.substring(0, 1));
           tfmm.setText(duration.substring(2, 4));
           
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbtvshow = new javax.swing.JComboBox<>();
        tftitle = new javax.swing.JTextField();
        lbvideopath = new javax.swing.JLabel();
        lbcoverphoto = new javax.swing.JLabel();
        lbsquarephoto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfhh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfmm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btvideobrowse = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btcoverbrowse = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btsquarebrowse = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btaddepisode = new javax.swing.JButton();

        cbtvshow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cbtvshow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbtvshowActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("HH:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("MM:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Select TV Show");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Title");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Video Path");

        btvideobrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btvideobrowse.setText("Browse...");
        btvideobrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btvideobrowseActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cover Photo");

        btcoverbrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcoverbrowse.setText("Browse...");
        btcoverbrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btcoverbrowseActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Square Photo");

        btsquarebrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btsquarebrowse.setText("Browse...");
        btsquarebrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btsquarebrowseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Duration");

        btaddepisode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btaddepisode.setText("Add Episode");
        btaddepisode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btaddepisodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(cbtvshow, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(tftitle, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btvideobrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)
                            .addComponent(lbvideopath, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btcoverbrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)
                            .addComponent(lbcoverphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btsquarebrowse))
                            .addGap(6, 6, 6)
                            .addComponent(lbsquarephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addComponent(jLabel4)
                            .addGap(6, 6, 6)
                            .addComponent(tfhh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5)
                            .addGap(4, 4, 4)
                            .addComponent(tfmm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(btaddepisode, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbtvshow, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tftitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btvideobrowse))
                        .addComponent(lbvideopath, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(btcoverbrowse))
                        .addComponent(lbcoverphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(btsquarebrowse))
                        .addComponent(lbsquarephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(tfhh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfmm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(btaddepisode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtvshowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbtvshowActionPerformed
    {//GEN-HEADEREND:event_cbtvshowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtvshowActionPerformed

    private void btvideobrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btvideobrowseActionPerformed
    {//GEN-HEADEREND:event_btvideobrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                lbvideopath.setText(f.getPath());

            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btvideobrowseActionPerformed

    private void btcoverbrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btcoverbrowseActionPerformed
    {//GEN-HEADEREND:event_btcoverbrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                lbcoverphoto.setText(f.getPath());
                Image img = ImageIO.read(f).getScaledInstance(lbcoverphoto.getWidth(), lbcoverphoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbcoverphoto.setIcon(icon);
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btcoverbrowseActionPerformed

    private void btsquarebrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btsquarebrowseActionPerformed
    {//GEN-HEADEREND:event_btsquarebrowseActionPerformed
        try
        {
            JFileChooser jfilechooser = new JFileChooser();
            int ans = jfilechooser.showOpenDialog(this);
            if (ans == 0)
            {
                f = jfilechooser.getSelectedFile();
                lbsquarephoto.setText(f.getPath());
                Image img = ImageIO.read(f).getScaledInstance(lbsquarephoto.getWidth(), lbsquarephoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbsquarephoto.setIcon(icon);
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btsquarebrowseActionPerformed

    private void btaddepisodeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btaddepisodeActionPerformed
    {//GEN-HEADEREND:event_btaddepisodeActionPerformed
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod", "root", "system");
           Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
           String tvshow = cbtvshow.getSelectedItem() + "";
        String title = tftitle.getText();
        String videopath = lbvideopath.getText();
        String coverphoto = lbcoverphoto.getText();
        String squarephoto = lbsquarephoto.getText();
        String duration = tfhh.getText() + ":" + tfmm.getText();
        if (title.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Title field");
        } else if (videopath.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Video Path field");
        } else if (coverphoto.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Cover Photo field");
        } else if (squarephoto.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill the Square Photo field");
        } else if (duration.equals(":"))
        {
            JOptionPane.showMessageDialog(this, "Please fill the Duration field");
        } else
        {
            
                
                ResultSet rs = stmt.executeQuery("select * from episodes where eid='"+eid+"'");
                
                rs.updateString("title", title);
                rs.updateString("videopath", videopath);
                rs.updateString("cover", coverphoto);
                rs.updateString("square", squarephoto);
                rs.updateString("duration", duration);
                rs.updateRow();
                JOptionPane.showMessageDialog(this, "Episode Updated");
                this.dispose();
            }      
        } catch (Exception e)
            {
                e.printStackTrace();
            }
        
    }//GEN-LAST:event_btaddepisodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddepisode;
    private javax.swing.JButton btcoverbrowse;
    private javax.swing.JButton btsquarebrowse;
    private javax.swing.JButton btvideobrowse;
    private javax.swing.JComboBox<String> cbtvshow;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbcoverphoto;
    private javax.swing.JLabel lbsquarephoto;
    private javax.swing.JLabel lbvideopath;
    private javax.swing.JTextField tfhh;
    private javax.swing.JTextField tfmm;
    private javax.swing.JTextField tftitle;
    // End of variables declaration//GEN-END:variables
}
