
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class LaunchMovies extends javax.swing.JFrame
{

    /**
     * Creates new form LaunchMovies
     */
    Movies m;
    public LaunchMovies(Movies m)
    {
        this.m=m;
        
        initComponents();
        System.out.println("coverphoto="+m.coverphoto);
        String photo="C:\\Users\\hp\\Documents\\NetBeansProjectsv\\VideoOnDemand\\images\\play.png";
       // lbcover.setText(m.coverphoto);
       // lbsquare.setText(m.squarephoto);
        try
        {
            Image img = ImageIO.read(new File(m.coverphoto)).getScaledInstance(lbcover.getWidth(),lbcover.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon icon = new ImageIcon(img);
                        lbcover.setIcon(icon);
            Image img1 = ImageIO.read(new File(m.squarephoto)).getScaledInstance(lbsquare.getWidth(),lbsquare.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon icon1 = new ImageIcon(img1);
                        lbsquare.setIcon(icon1);
                        
            Image img2 = ImageIO.read(new File(photo)).getScaledInstance(lbplay.getWidth(),lbplay.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon icon2 = new ImageIcon(img2);
                        lbplay.setIcon(icon2);
                        
        } catch (Exception e)
        {
        }
        lbtitle.setText(m.movietitle);
        lbproducer.setText(m.producer);
        lbdirector.setText(m.director);
        lbrating.setText(m.rating);
        lbdate.setText(m.releasedate);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbsquare = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbtitle = new javax.swing.JLabel();
        lbdirector = new javax.swing.JLabel();
        lbproducer = new javax.swing.JLabel();
        lbrating = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        lbplay = new javax.swing.JLabel();
        lbcover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbsquare.setText("jLabel1");
        getContentPane().add(lbsquare);
        lbsquare.setBounds(30, 127, 199, 92);

        jLabel2.setText("Title");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 252, 78, 24);

        jLabel3.setText("Director");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 294, 78, 23);

        jLabel4.setText("Producer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 345, 78, 24);

        jLabel5.setText("Rating");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 398, 78, 23);

        jLabel6.setText("Release Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 439, 78, 24);

        lbtitle.setText("jLabel7");
        getContentPane().add(lbtitle);
        lbtitle.setBounds(106, 252, 110, 24);

        lbdirector.setText("lbdirector");
        getContentPane().add(lbdirector);
        lbdirector.setBounds(106, 294, 110, 23);

        lbproducer.setText("jLabel9");
        getContentPane().add(lbproducer);
        lbproducer.setBounds(106, 345, 120, 24);

        lbrating.setText("jLabel10");
        getContentPane().add(lbrating);
        lbrating.setBounds(106, 398, 130, 23);

        lbdate.setText("jLabel11");
        getContentPane().add(lbdate);
        lbdate.setBounds(106, 439, 140, 24);

        lbplay.setText("jLabel12");
        lbplay.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbplayMouseClicked(evt);
            }
        });
        getContentPane().add(lbplay);
        lbplay.setBounds(337, 335, 115, 45);

        lbcover.setText("jLabel13");
        getContentPane().add(lbcover);
        lbcover.setBounds(10, 11, 610, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbplayMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbplayMouseClicked
    {//GEN-HEADEREND:event_lbplayMouseClicked
        String vpath=m.videopath;
        VLCFrame playframe=new VLCFrame(vpath);
        playframe.setVisible(true);
    }//GEN-LAST:event_lbplayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LaunchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LaunchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LaunchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LaunchMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
              //  new LaunchMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbcover;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbdirector;
    private javax.swing.JLabel lbplay;
    private javax.swing.JLabel lbproducer;
    private javax.swing.JLabel lbrating;
    private javax.swing.JLabel lbsquare;
    private javax.swing.JLabel lbtitle;
    // End of variables declaration//GEN-END:variables
}
