
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.net.Socket;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static javax.swing.JFrame.EXIT_ON_CLOSE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class ViewAllMovies extends javax.swing.JFrame
{

    ArrayList<Movies> al=new ArrayList<>();
    public ViewAllMovies(ArrayList<Movies>al)
    {   
        this.setLayout(null);
        initComponents();
        this.setBackground(Color.white);
        lbMovies.setBackground(Color.BLUE);
        this.setTitle("Watch Movies");
        this.setVisible(true);
        jPanel1.setVisible(true);
        jScrollPane1.setVisible(true);
        this.setSize(1024,718);
        jPanel1.setSize(1024,718);
        jScrollPane1.setSize(1024,718);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.al=al;
        new Thread(new getAllMovies()).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbMovies = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbMovies.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMovies.setText("                                                                          Movies");
        getContentPane().add(lbMovies);
        lbMovies.setBounds(0, 0, 796, 28);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 46, 776, 364);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
               // new ViewAllMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMovies;
    // End of variables declaration//GEN-END:variables
    
    class getAllMovies implements Runnable
    {
      int x=10;
      int y=10;
      ArrayList<String> alGenre=new ArrayList<>(); 
      public void run()
      {
        try
        {
            Socket sock=new Socket("127.0.0.1",4200);
            DataOutputStream dos = new DataOutputStream(sock.getOutputStream());
            DataInputStream dis = new DataInputStream(sock.getInputStream());
            dos.writeBytes("sendgenre\r\n");
            String response=dis.readLine();
            System.out.println(response);
            if(response.equals("receive"))
            {
                String rsp=response;
                rsp=dis.readLine();
                while(!rsp.equals("done"))
                {
                    
                      alGenre.add(rsp+"");
                      rsp=dis.readLine();
                      
                }
               
            }
            
            int height=alGenre.size()*300;
            jScrollPane1.setSize(getWidth()-50,height);
            jPanel1.setSize(getWidth()-50, height);
            for(int i=0;i<=alGenre.size();i++)
            {
                String genre=alGenre.get(i);
                showPanel(genre,al);
            }
        } 
        catch (Exception e)
        {
        }  
      }
      
    
      public void showPanel(String genre,ArrayList<Movies>al)
      {   int x=10;
          int y=10;
          
          GeneredVideo gv=new GeneredVideo();
          gv.setSize(jPanel1.getWidth(),50);
          gv.lbGenre.setText(genre);
          gv.lbGenre.setBackground(Color.red);
          gv.setBounds(this.x,this.y,jScrollPane1.getWidth()-40,182);
//          for(int i=0;i<=al.size()-1;i++)
//          {
//             Movies m=al.get(i);
//             SingleMovie sm=new SingleMovie(m);
//             sm.setBounds(x,10,280,120);
//             gv.jpall.add(sm);
//             gv.jpall.repaint();
//             x=x+290;
//          }
          gv.setVisible(true);
          jPanel1.add(gv);
          for(int i=0;i<=al.size()-1;i++)
          {
             if(al.get(i).genre.equals(genre))
             {
               Movies m=al.get(i);
             String coverphoto=m.coverphoto;
             SingleMovie sm=new SingleMovie(m);
             sm.setBounds(x,10,280,120);
              try
              {
                  Image img = ImageIO.read(new File(coverphoto)).getScaledInstance(sm.getWidth(),sm.getHeight(), Image.SCALE_SMOOTH);
                  ImageIcon icon = new ImageIcon(img);
                  sm.lbmovies.setIcon(icon);
                  sm.addMouseListener(new MouseAdapter()
                  {
                    public void mouseClicked(MouseEvent e)
                    {
                        LaunchMovies launchmovies=new LaunchMovies(m);
                        launchmovies.setVisible(true);
                        launchmovies.setSize(650,530);
                              
                     }
                   });
              } catch (Exception e)
              {
              }
             gv.jpall.add(sm);
             gv.jpall.repaint();
             x=x+290;  
             }
             
          }
          jPanel1.repaint();
          this.y=this.y+200;
      }
    }
}
