
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

public class ViewTVShow extends javax.swing.JInternalFrame
{

    ArrayList<Genre> al;
    MyProjectModel tm;
    public ViewTVShow()
    {
        initComponents();
        cbSelectGenre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbgenre = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtviewtvshow = new javax.swing.JTable();
        btedit = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btrefresh = new javax.swing.JButton();

        getContentPane().setLayout(null);

        cbgenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cbgenre.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbgenreItemStateChanged(evt);
            }
        });
        getContentPane().add(cbgenre);
        cbgenre.setBounds(210, 20, 338, 38);

        jLabel1.setText("Select Genre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(33, 21, 167, 37);

        jtviewtvshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtviewtvshow);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(33, 69, 515, 185);

        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit);
        btedit.setBounds(30, 270, 144, 40);

        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete);
        btdelete.setBounds(410, 270, 137, 40);

        btrefresh.setText("Refresh");
        btrefresh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btrefresh);
        btrefresh.setBounds(230, 270, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbgenreItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbgenreItemStateChanged
    {//GEN-HEADEREND:event_cbgenreItemStateChanged
      String selectgenre=cbgenre.getSelectedItem()+"";
       al=new ArrayList<>();
       int s=1;
        try
        {
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod","root","system");
         Statement stmt=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
         ResultSet rs=stmt.executeQuery("select * from video where genre='"+selectgenre+"'AND cname='"+"TV Shows"+"'");
         while(rs.next())
         {
             al.add(new Genre(s,rs.getString("cname"),rs.getString("genre"),rs.getString("producer"),rs.getString("director"),rs.getString("storyline"),rs.getString("releasedate"),rs.getString("id"),rs.getString("title"),
                     rs.getString("duration"),rs.getString("rating"),rs.getString("language"),rs.getString("coverphoto"),rs.getString("cast"),rs.getString("squarephoto"),rs.getString("videopath"),rs.getString("trailerpath")));
             s++;
         }
         
         tm=new MyProjectModel();
         jtviewtvshow.setModel(tm);
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_cbgenreItemStateChanged

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btdeleteActionPerformed
    {//GEN-HEADEREND:event_btdeleteActionPerformed
        int index=jtviewtvshow.getSelectedRow();
        if(index==-1)
        {
            JOptionPane.showMessageDialog(this,"Please select 'Movie' first to delete");
        }
        else
        {
          String title=al.get(index).movietitle;
          
          if(JOptionPane.showConfirmDialog
                           (this,"Are you sure you want to delete the Movie '"+title+"'","Delete",JOptionPane.YES_NO_OPTION)==0)
          {
              try
              {
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod","root","system");
                 Statement stmt=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                 ResultSet rs=stmt.executeQuery("select * from video where title='"+title+"'");
                 if(rs.next())
                 {
                     rs.deleteRow();
                     al.remove(jtviewtvshow.getSelectedRow());
                     tm.fireTableDataChanged();
                     JOptionPane.showMessageDialog(this, "Record Deleted");
                 }
              }
              catch (Exception e)
              {
                  e.printStackTrace();
              }
          }
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bteditActionPerformed
    {//GEN-HEADEREND:event_bteditActionPerformed
        int index=jtviewtvshow.getSelectedRow();
       if(index==-1)
       {
           JOptionPane.showMessageDialog(this, "Please select the Video to edit");
       }
       else if(index!=-1)
       {
           EditTvShow obj=new EditTvShow(al.get(index).genre,al.get(index).producer,al.get(index).director,al.get(index).storyline,al.get(index).id,al.get(index).movietitle,al.get(index).duration
                                               ,al.get(index).rating,al.get(index).language,al.get(index).coverphoto,al.get(index).squarephoto);
           obj.setIconifiable(true);
           obj.setMaximizable(true);
           obj.setClosable(true);
           obj.setSize(960,574);
           this.getDesktopPane().add(obj);
           obj.moveToFront();
           obj.setVisible(true);
       }
    }//GEN-LAST:event_bteditActionPerformed

    private void btrefreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btrefreshActionPerformed
    {//GEN-HEADEREND:event_btrefreshActionPerformed
        String selectgenre=cbgenre.getSelectedItem()+"";
        al.clear();
        int s=1;
        try
        {
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod","root","system");
         Statement stmt=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
         ResultSet rs=stmt.executeQuery("select * from video where genre='"+selectgenre+"'AND cname='"+"TV Shows"+"'");
         while(rs.next())
         {
             al.add(new Genre(s,rs.getString("cname"),rs.getString("genre"),rs.getString("producer"),rs.getString("director"),rs.getString("storyline"),rs.getString("releasedate"),rs.getString("id"),rs.getString("title"),
                     rs.getString("duration"),rs.getString("rating"),rs.getString("language"),rs.getString("coverphoto"),rs.getString("cast"),rs.getString("squarephoto"),rs.getString("videopath"),rs.getString("trailerpath")));
             s++;
         }
         
         tm=new MyProjectModel();
         jtviewtvshow.setModel(tm);
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btrefresh;
    private javax.swing.JComboBox<String> cbgenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtviewtvshow;
    // End of variables declaration//GEN-END:variables
   
     void cbSelectGenre()
   {
     try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod","root","system");
        Statement stmt=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        ResultSet rs=stmt.executeQuery("select * from genre");
        while(rs.next())
        {
            String selectgenre=rs.getString("Genre Name");
            cbgenre.addItem(selectgenre);
            
        }
        }
        catch(Exception ex)
        {
            
        }   
   }
   
   
   class Genre
   {
       int s;
       
       String cname;
       String genre;
       String producer;
       String director;
       String releasedate;
       String id;
       String storyline;
       String rating;
       String coverphoto;
       String cast;
       String squarephoto;
       String movietitle;
       String videopath;
       String trailerpath;
       String duration;
       String language;
       
       Genre(int s,String cname,String genre,String producer,String director,String storyline,String releasedate,String id,String movietitle,String duration,String rating,String language,String coverphoto,String cast,String squarephoto,String videopath,String trailerpath)
       {
           this.s=s;
           this.cname=cname;
           this.genre=genre;
           this.director=director;
           this.producer=producer;
           this.releasedate=releasedate;
           this.id=id;
           this.storyline=storyline;
           this.rating=rating;
           this.squarephoto=squarephoto;
           this.cast=cast;
           this.coverphoto=coverphoto;
           this.movietitle=movietitle;
           this.videopath=videopath;
           this.trailerpath=trailerpath;
           this.duration=duration;
           this.language=language;
       }
           
    }
   
   class MyProjectModel extends AbstractTableModel
   {
       String name[]={"S.No.","TVShow Title","Director","Producer","Language"};
       public int getRowCount()
       {
         return al.size();  
       }
       public int getColumnCount()
       {
         return 5;
       }
       public Object getValueAt(int row,int col)
       {  
          Genre g=al.get(row);
          if(col==0)
          {
             return g.s;
          }
          else if(col==1)
          {
              return g.movietitle;
          }
          else if(col==2)
          {
              return g.director;
          }
          else if(col==3)
          {
              return g.producer;
          }
          else
          {
              return g.language;   
          }
       }
       public String getColumnName(int col)
       {
          return name[col]; 
       }
   }
}
